# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '3'

services:
  relayerA:
    network_mode: host
    image: chainsafe/chainbridge-core-example:evm-celo-dev
    restart: unless-stopped
    container_name: relayerA
    ports:
      - "8002:8001"
      - "2112:2112"
    volumes:
      - ./blockstoreA:/blockstore
      - ./configA:/config
      - ./keys:/keys
    environment:
      - KEYSTORE_PASSWORD=1234567890
      - BLOCK_TIMEOUT=300
    command:
      - --config=/config/
      - --keystore=/keys
      - --blockstore=/blockstoreA
      - --latest

  relayerB:
    network_mode: host
    image: chainsafe/chainbridge-core-example:evm-celo-dev
    restart: unless-stopped
    container_name: relayerB
    ports:
      - "8003:8001"
      - "2212:2112"
    volumes:
      - ./blockstoreB:/blockstore
      - ./configB:/config
      - ./keys:/keys
    environment:
      - KEYSTORE_PASSWORD=1234567890
      - BLOCK_TIMEOUT=300
    command:
      - --config=/config/
      - --keystore=/keys
      - --blockstore=/blockstoreB
      - --latest
#    networks:

  relayerC:
    network_mode: host
    image: chainsafe/chainbridge-core-example:evm-celo-dev
    restart: unless-stopped
    container_name: relayerC
    ports:
      - "8004:8001"
      - "2312:2112"
    volumes:
      - ./blockstoreC:/blockstore
      - ./configC:/config
      - ./keys:/keys
    environment:
      - KEYSTORE_PASSWORD=1234567890
      - BLOCK_TIMEOUT=300
    command:
      - --config=/config/
      - --keystore=/keys
      - --blockstore=/blockstoreC
      - --latest
