# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '3'

services:
  celo:
    image: "chainsafe/chainbridge-bootstrapped-celo:v1.0.0"
    container_name: celo
    ports:
      - "8546:8545"
  
  geth:
    image: "chainsafe/chainbridge-geth:20200505131100-5586a65"
    container_name: geth
    ports:
      - "8545:8545"
