# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '3'

services:
  celo1:
    image: "chainsafe/chainbridge-celo-blockchain:0.1.4"
    networks:
      - celo
    container_name: celo1
    ports:
      - "8545:8545"
      - "8546:8546"
    environment:
      - NODEKEY=98ab333347a12cef869f92b3de44085f9e44891e513bcf1d76a99eecbcdd5e17
      - DATADIR=celo-dump1
      - NETWORKID=333
      - VALIDATOR=0xf4314cb9046bece6aa54bb9533155434d0c76909

  evm1:
    build:
      context: ./e2e/geth-build
      dockerfile: Dockerfile
    container_name: evm1
    networks:
      - evm
    ports:
      - "8845:8545"
      - "8846:8546"
    environment:
      - NODEKEY=98ab333347a12cef869f92b3de44085f9e44891e513bcf1d76a99eecbcdd5e17
      - NETWORKID=420
      - MINE=true
    entrypoint: "/root/entrypoint.sh"

  relayer1:
    container_name: relayer1
    build:
      context: .
      dockerfile: Dockerfile
    command: run --config /cfg/evm_celo-config.json --testkey alice --fresh
    depends_on:
      - evm1
      - celo1
    networks:
      - evm
      - celo
    volumes:
      - ./example/cfg:/cfg

  relayer2:
    container_name: relayer2
    build:
      context: .
      dockerfile: Dockerfile
    command: run --config /cfg/evm_celo-config.json --testkey bob --fresh
    depends_on:
      - evm1
      - celo1
    networks:
      - evm
      - celo
    volumes:
      - ./example/cfg:/cfg

  relayer3:
    container_name: relayer3
    build:
      context: .
      dockerfile: Dockerfile
    command: run --config /cfg/evm_celo-config.json --testkey charlie --fresh
    depends_on:
      - evm1
      - celo1
    networks:
      - evm
      - celo
    volumes:
      - ./example/cfg:/cfg

networks:
  evm:
  celo:
