# Copyright 2021 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: chainbridge
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:2112']
